name: yooper
favicon: null
layout_spectrum: 0.6604
typography_spectrum: 0.88491
title: All About a Yooper
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 0.4493755172006786
  saturation: 0.8125
  rhythmicContrast: 0.5432137597817928
purpose: []
