name: yooper
favicon: null
layout_spectrum: 1
typography_spectrum: 0.96426
title: 'All About a Yooper - Well, according to the Merriam-Webster Dictionary we are "a native or inhabitant of the Upper Peninsula of Michigan."'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#91897c'
    - '#b0bab2'
    - '#e0e2dd'
    - '#4f514c'
    - '#0f0a04'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
