name: yooper
favicon: null
layout_spectrum: 0.45120148779824376
typography_spectrum: 0.7081749537028372
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3407943886704743
  lightness: 0.4493755172006786
  saturation: 0.4574860204011202
  rhythmicContrast: 0.5432137597817928
purpose: []
