name: yooper
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Pic descript of the U.P.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7fcf6'
    - '#020605'
    - '#6c6d5d'
    - '#5f1e26'
    - '#b3cad0'
  brandStrength: 0.375
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0
purpose: []
