name: yooper
favicon: null
layout_spectrum: 0.37692
typography_spectrum: 0
title: Pic descript of the U.P.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5c2a33'
    - '#abc5c6'
    - '#718b8c'
    - '#1d2528'
    - '#755723'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
